; ===========================
; Configuración de base de datos
; ===========================

DB_HOST = "localhost" ;servidor de base de datos
DB_NAME = "db_sysmanager" ;nombre de la base de datos
DB_USER = "root" ;usuario de la base de datos
DB_PASS = "" ;contraseña de la base de datos
DB_PORT = 3306 ;puerto de la base de datos