; ===========================
; Configuración de JWT
; ===========================

JWT_SECRET = "55d494e86f64fe309929816ede2c295ea5afa5bd0b8a4e336e51f53f77f70aef"
JWT_EXPIRATION = 3600  ;tiempo en segundos (1 hora)
