; ===========================
; Configuración de JWT
; ===========================

JWT_SECRET = "solucionesITEC2026" ;nombre de la empresa o proyecto
JWT_EXPIRATION = 3600  ;tiempo en segundos (1 hora)
