; ===========================
; Configuración de correo SMTP
; ===========================

MAIL_HOST     = "smtp.hostinger.com"
MAIL_PORT     = 465
MAIL_USERNAME = "info@solucionesitec.com"
MAIL_PASSWORD = "InfoHostinger2024*/"
MAIL_FROM     = "info@solucionesitec.com"
MAIL_FROM_NAME = "SolucionesITEC"
